version: '3.8' # เพิ่มระบุเวอร์ชันตรงนี้

services:
  ocr-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-ocr-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
    restart: unless-stopped
    # สังเกตว่าไม่มีการใช้ volumes เพื่อเมาท์โฟลเดอร์โค้ดแล้ว